[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/stevefan1999-personal/inkwell.git"]
git = "https://github.com/stevefan1999-personal/inkwell.git"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"