[workspace]
members = [
    "tpde",
    "tpde-encodegen",
    "tpde-llvm"
]

resolver = "2"

[workspace.dependencies]
inkwell = { version = "0.6", features = ["llvm18-1"] }
object = { version = "0.37", features = ["all"] }
