[workspace]
members = [
    "tpde",
    "tpde-encodegen",
    "tpde-llvm"
]

resolver = "2"

[workspace.dependencies]
inkwell = { version = "0.2" }
object = { version = "0.32" }
cbindgen = { version = "0.26" }
