[package]
name = "tpde-llvm"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { workspace = true }
llvm-sys = { workspace = true }
tpde-core = { path = "../tpde-core" }

[lib]
path = "src/lib.rs"
